# -*- coding: utf-8 -*-
"""prakalgo12.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdUXADJ0NuPo_vRkqyQ17Eyfd2lpMScE
"""

def binary_search(arr, target):
    low, high = 0, len(arr) - 1

    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid  # Ditemukan
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1

    return -1  # Tidak Ditemukan

def main():
    jumlah_angka = int(input("Masukkan jumlah angka pada List: "))
    angka_list = []

    for i in range(1, jumlah_angka + 1):
        angka = int(input(f"Angka ke-{i}: "))
        angka_list.append(angka)

    angka_list.sort()  # Binary Search memerlukan list terurut
    print("List angka >", angka_list)

    angka_dicari = int(input("Masukkan angka yang dicari: "))

    result = binary_search(angka_list, angka_dicari)

    if result != -1:
        print(f"Hasil Binary Search -> Ditemukan (di index {result})")
    else:
        print("Hasil Binary Search -> Tidak Ditemukan")

if __name__ == "__main__":
    main()