# -*- coding: utf-8 -*-
"""prakalgo12.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xCUCFsn2E6fYKec-vOrcmTyojYkXzw_-
"""

def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return True  # Ditemukan
    return False  # Tidak Ditemukan

def main():
    jumlah_angka = int(input("Masukkan jumlah angka pada List: "))
    angka_list = []

    for i in range(1, jumlah_angka + 1):
        angka = int(input(f"Angka ke-{i}: "))
        angka_list.append(angka)

    print("List angka >", angka_list)

    angka_dicari = int(input("Masukkan angka yang dicari: "))

    if linear_search(angka_list, angka_dicari):
        print("Hasil Linear Search -> Ditemukan")
    else:
        print("Hasil Linear Search -> Tidak Ditemukan")

if __name__ == "__main__":
    main()